version: '3.4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    build: .
